"""
Plugin 10010: Entra Connect Synchronization Server Is a Domain Controller

Identifies the host running Microsoft Entra Connect (or legacy Azure AD
Connect / DirSync) and reports when that host is a domain controller.

The sync account's description is machine-generated by the Entra Connect
installer and names the host it runs on, in the form:

    "Account created by Microsoft Azure Active Directory Connect with
     installation identifier <hex> running on computer <HOSTNAME>
     configured to synchronize to tenant <tenant>."

or, for the AAD_ service account variant:

    "Service account for the Synchronization Service with installation
     identifier <guid> running on computer <HOSTNAME>."

That host name is parsed out and matched against collected computer objects.
No new collection is required -- the string is already in ad_user.description.

Why it matters
--------------
The on-premises sync account holds directory replication rights on the domain
root by design, because password hash synchronisation requires them. That
makes the Entra Connect server a Tier 0 asset: anyone with administrative
access to it can recover the credential and DCSync the domain. Microsoft's
guidance is therefore to treat the sync server as a Tier 0 system and
explicitly advises against installing Entra Connect on a domain controller.

When the sync server *is* a domain controller, the separation that guidance
depends on does not exist. The credential with replication rights lives on
the machine it would replicate from, the sync service's local administrators
are effectively domain administrators, and the blast radius of any
compromise of the sync software -- for example CVE-2026-65673, the August
2026 Entra Connect local privilege escalation -- extends directly to the
directory rather than to an isolated member server.

CISA's AA26-237A assessment reached a cloud tenant precisely by pivoting
through sync infrastructure, which is what makes the placement of this host
worth auditing rather than assuming.

Relationship to plugin 10009
----------------------------
10009 reports the sync *account's* credential hygiene -- password age, SPNs,
whether replication rights are confirmed. This reports where that credential
physically lives. They are complementary: a well-rotated credential on a
domain controller is still a Tier 0 collapse, and a stale credential on a
properly isolated server is a different problem with a different fix.

Findings are aggregated one per host rather than one per sync account: a
domain controller may carry several (a current MSOL_ account plus an AAD_
service account, or an orphan left behind by a reinstall), and the host is
both the subject of the finding and the unit of remediation.

Silent when Entra Connect is not deployed, when the description does not
follow the installer's format (for example, an administrator overwrote it),
or when the named host cannot be matched to a collected computer object --
the last case usually meaning the sync server is not domain-joined to this
domain, which is itself fine.

[v1.1] The ADSyncMSA% name branch was removed: managed service accounts are
collected into ad_computer, never ad_user, so it could never match.
Liveness: uninstalling Entra Connect (or migrating it off the DC via
staging mode, as the remediation advises) leaves the old MSOL_/AAD_ account
and its description behind. A host is now reported at full severity
(fail, high/critical) only when at least one of its sync accounts is
enabled and has logged on within 30 days of the audited run
(lastLogonTimestamp, which lags up to ~14 days). When every matching
account is disabled or dormant the finding is a medium warn worded
"possibly orphaned". Replication rights are confirmed with the real DCSync
test (v_privileged_principal 'dcsync' / 'dcsync_via_group').
"""

PLUGIN = {
    "plugin_id": 10010,
    "category": "Hybrid Identity",
    "name": "Entra Connect Synchronization Server Is a Domain Controller",
    "version": "1.1",
    "revision_date": "2026-10-04",
    "remediation": (
        "Move Entra Connect off the domain controller onto a dedicated, "
        "hardened member server that is administered as a Tier 0 asset. "
        "Microsoft supports this migration through a staging-mode "
        "deployment: stand up Entra Connect on the new server in staging "
        "mode, let it complete a full synchronisation cycle and compare the "
        "pending export against the live server, then switch the new server "
        "out of staging mode and decommission the old installation. Done "
        "this way there is no synchronisation outage and no risk of a "
        "duplicate-write conflict. "
        "Do not simply uninstall and reinstall: a fresh installation creates "
        "a new MSOL_ account and can orphan the existing one, leaving a "
        "second account with directory replication rights that nobody is "
        "tracking. If that has already happened, plugin 10009 will list "
        "every sync account present -- more than one enabled MSOL_ account "
        "usually means an old installation was never cleaned up, and the "
        "stale one should be disabled and then removed. "
        "Until the move is complete, treat the domain controller's local "
        "administrators and the sync service account as equivalent to Domain "
        "Admins, restrict interactive logon to that host accordingly, and "
        "keep Entra Connect patched -- CVE-2026-65673 is a local privilege "
        "escalation in Entra Connect Sync fixed in 2.6.84.0, and on a domain "
        "controller a local escalation is a domain escalation. "
        "Where the new server is built, apply the same controls used for "
        "domain controllers: no general server-administration group with "
        "local admin, no co-located roles, restricted network access, and "
        "credential rotation on a defined schedule."
    ),
    "control_id": "HYBRID-410",
    "framework_tags": ["CISA-AA26-237A", "MITRE-ATTCK-T1003.006",
                       "MITRE-ATTCK-T1078.004", "MITRE-ATTCK-T1556"],
    "references": [
        {"title": "Microsoft: Entra Connect prerequisites and installation guidance",
         "url": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-prerequisites"},
        {"title": "Microsoft: Entra Connect Sync -- staging server and disaster recovery",
         "url": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sync-staging-server"},
        {"title": "CISA AA26-237A: Joint Red Team Assessment Findings",
         "url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa26-237a"},
    ],
    "description": (
        "Reports that Microsoft Entra Connect is installed on a domain "
        "controller. The host name is parsed from the machine-generated "
        "description on the MSOL_ or AAD_ synchronization account and matched "
        "against collected computer objects. Because the sync account holds "
        "directory replication rights on the domain root, its host is a Tier "
        "0 asset and Microsoft advises against co-locating it with a domain "
        "controller. Where they are the same machine, the sync service's "
        "local administrators are effectively domain administrators and any "
        "local privilege escalation in the sync software becomes a domain "
        "compromise. Complements plugin 10009, which reports the same "
        "account's credential hygiene rather than its placement. When "
        "every matching sync account is disabled or has not logged on "
        "within 30 days, the installation may already have been moved "
        "or removed and the finding is a medium warn (possibly orphaned "
        "account) instead."
    ),
    "base_severity": "high",
    "query": """
        WITH ref AS (
            SELECT COALESCE((SELECT completed_at FROM sync_run
                              WHERE run_id = %(run_id)s AND client_id = %(client_id)s),
                            now()) AS ref_time
        ),
        sync_account AS (
            SELECT u.object_guid,
                   u.sam_account_name,
                   u.description,
                   u.is_enabled,
                   u.pwd_last_set,
                   u.last_logon_timestamp,
                   do2.dn_current,
                   do2.object_sid,
                   -- Host name as written by the Entra Connect installer.
                   substring(u.description from 'running on computer ([^ .,;]+)')
                       AS sync_host
            FROM ad_user u
            JOIN directory_object do2
              ON do2.object_guid = u.object_guid AND do2.client_id = u.client_id
            WHERE u.client_id = %(client_id)s
              AND u.valid_to IS NULL
              AND u.description IS NOT NULL
              AND (
                    u.sam_account_name LIKE 'MSOL\\_%%'
                 OR u.sam_account_name LIKE 'AAD\\_%%'
                 OR u.description ILIKE '%%Azure AD Connect%%'
                 OR u.description ILIKE '%%Azure Active Directory Connect%%'
                 OR u.description ILIKE '%%Entra Connect%%'
                 OR u.description ILIKE '%%Synchronization Service%%'
              )
        ),
        replication_holder AS (
            -- [v1.1] Real DCSync (both rights / All Extended Rights /
            -- GenericAll, direct or via a group), per v_privileged_principal.
            SELECT DISTINCT pp.object_guid
            FROM v_privileged_principal pp
            WHERE pp.client_id = %(client_id)s
              AND pp.privilege_source IN ('dcsync', 'dcsync_via_group')
        ),
        resolved AS (
            SELECT sa.*,
                   c.object_guid AS host_guid,
                   c.sam_account_name AS host_sam,
                   c.dns_hostname,
                   c.operating_system,
                   c.is_domain_controller,
                   cdo.dn_current AS host_dn,
                   (rh.object_guid IS NOT NULL) AS replication_confirmed,
                   (sa.is_enabled IS TRUE
                    AND sa.last_logon_timestamp >= ref.ref_time - interval '30 days') AS is_live
            FROM sync_account sa
            CROSS JOIN ref
            JOIN ad_computer c
              ON c.client_id = %(client_id)s
             AND c.valid_to IS NULL
             AND (
                   upper(rtrim(c.sam_account_name, '$')) = upper(sa.sync_host)
                OR upper(split_part(COALESCE(c.dns_hostname, ''), '.', 1))
                   = upper(sa.sync_host)
             )
            JOIN directory_object cdo
              ON cdo.object_guid = c.object_guid AND cdo.client_id = c.client_id
            LEFT JOIN replication_holder rh ON rh.object_guid = sa.object_guid
            WHERE sa.sync_host IS NOT NULL
        ),
        agg AS (
            -- One row per host. A domain controller can carry more than one
            -- sync account -- a current MSOL_ account plus an AAD_ service
            -- account, or an orphan left by a reinstall -- and emitting a row
            -- each would produce several findings sharing one object_guid,
            -- which collides with the evidence table's one-open-version-per-
            -- identity constraint. The host is the subject of the finding and
            -- the unit of remediation, so aggregating is also the clearer
            -- output.
            SELECT r.host_guid,
                   min(r.host_sam) AS host_sam,
                   min(r.host_dn) AS host_dn,
                   min(r.dns_hostname) AS dns_hostname,
                   min(r.operating_system) AS operating_system,
                   min(r.sync_host) AS sync_host,
                   count(*) AS sync_account_count,
                   bool_or(r.replication_confirmed) AS any_replication_confirmed,
                   bool_or(r.is_live) AS any_live,
                   jsonb_agg(jsonb_build_object(
                       'sync_account', r.sam_account_name,
                       'sync_account_dn', r.dn_current,
                       'enabled', r.is_enabled,
                       'pwd_last_set', r.pwd_last_set,
                       'last_logon_timestamp', r.last_logon_timestamp,
                       'replication_rights_confirmed_on_domain_root',
                           r.replication_confirmed,
                       'recently_active', r.is_live,
                       'description', r.description
                   ) ORDER BY r.sam_account_name) AS sync_accounts
            FROM resolved r
            WHERE r.is_domain_controller
            GROUP BY r.host_guid
        )
        SELECT
            CASE WHEN a.any_live THEN 'fail' ELSE 'warn' END AS status,
            a.host_guid AS object_guid,
            NULL AS stig_severity,
            NULL AS stig_reference,
            NULL AS tool_severity,
            NULL AS tool_reference,
            CASE WHEN NOT a.any_live THEN 'medium'
                 WHEN a.any_replication_confirmed THEN 'critical'
                 ELSE 'high' END AS fd_severity,
            CASE WHEN a.any_live
            THEN 'Domain controller "' || COALESCE(a.host_sam, a.sync_host)
                || '" is running Entra Connect ('
                || a.sync_account_count || ' synchronization account(s): '
                || (SELECT string_agg(x.value ->> 'sync_account', ', '
                                      ORDER BY x.value ->> 'sync_account')
                    FROM jsonb_array_elements(a.sync_accounts) AS x)
                || ') -- the sync credential holds directory replication '
                   'rights and now lives on the domain controller it '
                   'replicates from'
                || CASE WHEN a.any_replication_confirmed
                        THEN ', and those replication rights are confirmed on '
                             'the domain root'
                        ELSE '' END
            ELSE 'Domain controller "' || COALESCE(a.host_sam, a.sync_host)
                || '" is named as the Entra Connect host by '
                || a.sync_account_count || ' disabled or dormant synchronization account(s) ('
                || (SELECT string_agg(x.value ->> 'sync_account', ', '
                                      ORDER BY x.value ->> 'sync_account')
                    FROM jsonb_array_elements(a.sync_accounts) AS x)
                || ') -- possibly an orphaned account from a moved or removed installation'
                || CASE WHEN a.any_replication_confirmed
                        THEN ' that still holds directory replication rights'
                        ELSE '' END
            END AS summary,
            jsonb_build_object(
                'sync_host_account', a.host_sam,
                'sync_host_dn', a.host_dn,
                'sync_host_dns_name', a.dns_hostname,
                'sync_host_operating_system', a.operating_system,
                'sync_host_parsed_from_description', a.sync_host,
                'sync_host_is_domain_controller', true,
                'sync_account_count', a.sync_account_count,
                'any_replication_rights_confirmed', a.any_replication_confirmed,
                'any_sync_account_recently_active', a.any_live,
                'sync_accounts', a.sync_accounts,
                'related_plugins', jsonb_build_array(10009, 5001)
            ) AS detail
        FROM agg a
    """,
}
